vim.api.nvim_create_user_command("CpRelPath", function()
    local path = vim.fn.expand("%")
    vim.fn.setreg("+", path)
    vim.notify('Copied "' .. path .. '" to the clipboard!')
end, {})

vim.api.nvim_create_user_command("CpAbsPath", function()
    local path = vim.fn.expand("%:p")
    vim.fn.setreg("+", path)
    vim.notify('Copied "' .. path .. '" to the clipboard!')
end, {})

vim.api.nvim_create_user_command("ShowRelPath", function()
    local path = vim.fn.expand("%")
    vim.notify('Relative path: ' .. path)
end, {})

vim.api.nvim_create_user_command("ShowAbsPath", function()
    local path = vim.fn.expand("%:p")
    vim.notify('Path: ' .. path)
end, {})
